data:
  n_categories: 3
  n_skus_per_category: 15
  n_days: 1460
  start_date: '2022-01-01'
preprocessing:
  min_skus_per_category: 10
  instock_threshold: 0.85
forecast:
  horizon_days: 7
decomposition:
  weekly_period: 7
  yearly_period: 365
  seasonal_smoothing: 13
  temp_sensitivity: 0.02
trend:
  smoothing_level: 0.8
  smoothing_trend: 0.2
  use_exponential_smoothing: true
features:
  lag_days:
  - 7
  - 14
  - 28
  rolling_windows:
  - 7
  - 28
  min_non_nan_pct: 0.1
lightgbm:
  objective: regression
  n_estimators: 369
  learning_rate: 0.09324055798383521
  max_depth: 7
  num_leaves: 59
  min_child_samples: 47
  subsample: 0.8489886688396073
  subsample_freq: 1
  colsample_bytree: 0.6962831044441021
  reg_alpha: 0.28351077714325923
  reg_lambda: 0.7757960310718994
  random_state: 42
validation:
  n_splits: 4
  gap_days: 0
  min_train_days: 180
optuna:
  n_trials: 50
  timeout_seconds: 3600
  lgbm_search_space:
    learning_rate:
    - 0.01
    - 0.1
    n_estimators:
    - 300
    - 1000
    max_depth:
    - 4
    - 12
    num_leaves:
    - 15
    - 63
    min_child_samples:
    - 10
    - 50
    subsample:
    - 0.6
    - 1.0
    colsample_bytree:
    - 0.6
    - 1.0
    reg_alpha:
    - 0.0
    - 1.0
    reg_lambda:
    - 0.0
    - 1.0
output:
  category_data: category_day_aggregated.csv
  pooled_data: pooled_training_data.csv
  forecasts: category_forecasts_30day.csv
  validation_metrics: validation_metrics.csv
  validation_predictions: validation_predictions.csv
  best_params: best_hyperparameters.yaml
visualization:
  lookback_days: 180
  dpi: 300
  figsize_per_category:
  - 16
  - 12
